data<- read.csv(file="WA_Fn-UseC_-Telco-Customer-Churn.csv")
mosaicplot(Churn~Contract,data=data)
mosaicplot(Churn~Contract+gender,data=data)
mosaicplot(Churn~Contract+SeniorCitizen,data=data)
mosaicplot(Churn~Contract+PhoneService,data=data)
mosaicplot(Churn~Contract+MultipleLines,data=data)
mosaicplot(Churn~Contract+PaperlessBilling,data=data)
mosaicplot(Churn~Contract+PaperlessBilling+PaymentMethod,data=data)
mosaicplot(Churn~Contract+PaymentMethod,data=data)
mosaicplot(Churn~gender+PaymentMethod,data=data)
mosaicplot(Churn~Dependents+PaymentMethod,data=data)
mosaicplot(Churn~Partner+Dependents+PaymentMethod,data=data)
mosaicplot(Churn~Dependents+PaymentMethod,data=data)
data$tenure_d <- cut(data$tenure,seq(0,120,6))
mosaicplot(Churn~Contract+PaymentMethod+tenure_d,data=data)
data$tenure_d <- cut(data$tenure,seq(0,120,24))
mosaicplot(Churn~Contract+PaymentMethod+tenure_d,data=data)
data$tenure_d <- cut(data$tenure,seq(0,90,24))
mosaicplot(Churn~Contract+PaymentMethod+tenure_d,data=data)
data$tenure_d <- cut(data$tenure,c(0,6,12,18,24,30,36,42,48,54,60,72,84,96,200))
mosaicplot(Churn~Contract+PaymentMethod+tenure_d,data=data)
data$tenure_d <- cut(data$tenure,c(0,6,12,24,36,48,60,84,200))
mosaicplot(Churn~Contract+PaymentMethod+tenure_d,data=data)

